### ISSUE TITLE
tutorial example code does not work: API credentials needed?

### ISSUE THREAD

**Issue by arnaudbouffard** [googlecodelabs/apps-script-intro#1]
I tweaked the script to populate a cell with the mapURL:

```
function sendMap() {
  var sheet = SpreadsheetApp.getActiveSheet();
  var address = sheet.getRange('A1').getValue();
  var map = Maps.newStaticMap().addMarker(address);
  sheet.getRange("A2").setValue(map.getMapUrl());
}
```

The script works, but the [url](http://maps.google.com/maps/api/staticmap?sensor=false&size=512x512&markers=new+york) leads to a page which displays the following html:

> The Google Maps Platform server rejected your request. You must use an API key to authenticate each request to Google Maps Platform APIs.

I could not find any info on where to set the Google Maps API key on Google Scripts documentation.

**Comment by wescpy** [comment]
Following-up:

-  In Jun 2016, the Google Maps team [announced](https://maps-apis.googleblog.com/2016/06/building-for-scale-updates-to-google.html) that keyless access to Maps has been deprecated.
- A [reminder](http://mapsplatform.googleblog.com/2018/05/introducing-google-maps-platform.html) was sent to users in May 2018
- Developers were given several years to migrate their apps, and enforcement began Jun 2018.
- The code in this repo is for the [Apps Script intro codelab](https://g.co/codelabs/apps-script-intro) whose code was updated Nov 2018.
- For some reason, the code in this repo wasn't updated at that time, so this is a valid issue.

**Comment by wescpy** [comment]
FIXED... the solution is rather than emailing a URL that's no longer valid, the code sample now attaches the map's image to the email message. Thx for the bug report!
